import van from "vanjs-core"
import style from "./utils/style"
import ActionLinkMenu from "./components/action-link-menu"
import H1 from "./components/h1"
import H2 from "./components/h2"
import P from "./components/p"
import H3 from "./components/h3"

const { a, div, li, p, ul, i, h1, h2, img, table, th, tbody, tr, hr } = van.tags

// Reusable components can be just pure vanilla JavaScript functions.
// Here we capitalize the first letter to follow React conventions.
const Skills = () => div(
  P(`Lorem ipsum dolor sit amet, consectetur adipiscing elit. In purus justo, aliquet et felis vel, finibus sollicitudin odio. Nullam massa lectus, rhoncus non feugiat eget, sollicitudin ut neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum et tellus bibendum, tempor lacus id, scelerisque sem. Vestibulum enim ipsum, interdum ac sem vel, facilisis venenatis ligula. Suspendisse a arcu et leo viverra euismod sed sit amet lacus. Suspendisse ac dolor porta, dictum arcu vel, suscipit tortor. Vivamus scelerisque libero ac purus sollicitudin congue. Donec a sem diam. In nec convallis felis. Praesent efficitur libero blandit turpis blandit finibus. Pellentesque fringilla lobortis aliquet. Praesent et ligula velit. Duis rutrum leo eget lectus ultrices, eget facilisis nunc condimentum. Pellentesque malesuada purus vitae commodo tristique. Cras vel posuere velit.

  Morbi laoreet venenatis lorem et mattis. Vestibulum id ex et nisl condimentum tincidunt eu sit amet urna. Phasellus quis orci ut tortor lobortis eleifend. Nulla convallis lacus mauris, et porttitor sem blandit nec. Aliquam suscipit ligula quis felis finibus, sed interdum urna ultrices. Quisque massa velit, pellentesque interdum dictum ut, egestas sed sapien. Nulla ultrices nunc at turpis laoreet accumsan. Aenean ex lacus, pellentesque et auctor vitae, mollis vel ligula. Nam nisi elit, mattis vitae tincidunt at, volutpat quis ex. Ut eu lectus ut sem efficitur posuere. Praesent pretium nulla lectus, luctus scelerisque risus sollicitudin eget. Nam euismod auctor dolor non blandit. Donec eu tristique turpis, vel ornare arcu.
  
  Vivamus posuere lorem tortor, in vulputate quam convallis eu. Nullam in mauris ex. Maecenas sollicitudin suscipit tellus vitae eleifend. In vitae felis ac mauris malesuada dignissim. In vulputate molestie dolor eget laoreet. Nunc sagittis accumsan felis, at molestie sapien lobortis vel. Nunc volutpat in velit nec pretium. Sed porta posuere orci, ac varius est. Nam viverra diam eu consectetur sagittis. Vivamus porta faucibus ex quis sodales.
  
  Maecenas volutpat feugiat leo ut elementum. Praesent ac orci sit amet mauris blandit semper. Fusce nibh ex, accumsan vitae odio vel, cursus scelerisque lectus. Pellentesque dignissim lacus aliquam sagittis egestas. Pellentesque elementum, augue eget commodo rhoncus, augue diam imperdiet diam, sed vehicula nunc nisi facilisis nulla. In quis lacus at enim imperdiet interdum. Etiam non nulla laoreet, aliquam ex non, vulputate sem. Donec ultricies ex eget nulla ullamcorper imperdiet. Pellentesque eget ex nec ante feugiat aliquet quis nec lacus. In porta rutrum magna, sagittis bibendum sapien auctor id. Sed nec nisi vitae nibh auctor tempor vitae at eros. Donec mauris felis, gravida pellentesque luctus quis, venenatis sed tellus. Ut id bibendum justo. Praesent porttitor felis eu volutpat rhoncus. Ut ut vehicula mi, et aliquam ante.
  
  Vivamus sed ultricies neque. Donec quis varius lorem, quis volutpat velit. Etiam sed feugiat erat. Praesent gravida enim eu odio rutrum ullamcorper. In vitae nibh at erat luctus vehicula. Donec tincidunt felis ac augue iaculis malesuada. Pellentesque elit leo, porttitor nec vestibulum non, imperdiet in velit. Vestibulum lacinia mi nec purus condimentum consectetur. Fusce in urna non erat congue pulvinar. Aliquam erat volutpat. Nam ac luctus purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum sed venenatis enim. Nullam auctor nunc sit amet velit egestas, fringilla gravida nisl aliquet.
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. In purus justo, aliquet et felis vel, finibus sollicitudin odio. Nullam massa lectus, rhoncus non feugiat eget, sollicitudin ut neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum et tellus bibendum, tempor lacus id, scelerisque sem. Vestibulum enim ipsum, interdum ac sem vel, facilisis venenatis ligula. Suspendisse a arcu et leo viverra euismod sed sit amet lacus. Suspendisse ac dolor porta, dictum arcu vel, suscipit tortor. Vivamus scelerisque libero ac purus sollicitudin congue. Donec a sem diam. In nec convallis felis. Praesent efficitur libero blandit turpis blandit finibus. Pellentesque fringilla lobortis aliquet. Praesent et ligula velit. Duis rutrum leo eget lectus ultrices, eget facilisis nunc condimentum. Pellentesque malesuada purus vitae commodo tristique. Cras vel posuere velit.

Morbi laoreet venenatis lorem et mattis. Vestibulum id ex et nisl condimentum tincidunt eu sit amet urna. Phasellus quis orci ut tortor lobortis eleifend. Nulla convallis lacus mauris, et porttitor sem blandit nec. Aliquam suscipit ligula quis felis finibus, sed interdum urna ultrices. Quisque massa velit, pellentesque interdum dictum ut, egestas sed sapien. Nulla ultrices nunc at turpis laoreet accumsan. Aenean ex lacus, pellentesque et auctor vitae, mollis vel ligula. Nam nisi elit, mattis vitae tincidunt at, volutpat quis ex. Ut eu lectus ut sem efficitur posuere. Praesent pretium nulla lectus, luctus scelerisque risus sollicitudin eget. Nam euismod auctor dolor non blandit. Donec eu tristique turpis, vel ornare arcu.

Vivamus posuere lorem tortor, in vulputate quam convallis eu. Nullam in mauris ex. Maecenas sollicitudin suscipit tellus vitae eleifend. In vitae felis ac mauris malesuada dignissim. In vulputate molestie dolor eget laoreet. Nunc sagittis accumsan felis, at molestie sapien lobortis vel. Nunc volutpat in velit nec pretium. Sed porta posuere orci, ac varius est. Nam viverra diam eu consectetur sagittis. Vivamus porta faucibus ex quis sodales.

Maecenas volutpat feugiat leo ut elementum. Praesent ac orci sit amet mauris blandit semper. Fusce nibh ex, accumsan vitae odio vel, cursus scelerisque lectus. Pellentesque dignissim lacus aliquam sagittis egestas. Pellentesque elementum, augue eget commodo rhoncus, augue diam imperdiet diam, sed vehicula nunc nisi facilisis nulla. In quis lacus at enim imperdiet interdum. Etiam non nulla laoreet, aliquam ex non, vulputate sem. Donec ultricies ex eget nulla ullamcorper imperdiet. Pellentesque eget ex nec ante feugiat aliquet quis nec lacus. In porta rutrum magna, sagittis bibendum sapien auctor id. Sed nec nisi vitae nibh auctor tempor vitae at eros. Donec mauris felis, gravida pellentesque luctus quis, venenatis sed tellus. Ut id bibendum justo. Praesent porttitor felis eu volutpat rhoncus. Ut ut vehicula mi, et aliquam ante.

Vivamus sed ultricies neque. Donec quis varius lorem, quis volutpat velit. Etiam sed feugiat erat. Praesent gravida enim eu odio rutrum ullamcorper. In vitae nibh at erat luctus vehicula. Donec tincidunt felis ac augue iaculis malesuada. Pellentesque elit leo, porttitor nec vestibulum non, imperdiet in velit. Vestibulum lacinia mi nec purus condimentum consectetur. Fusce in urna non erat congue pulvinar. Aliquam erat volutpat. Nam ac luctus purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum sed venenatis enim. Nullam auctor nunc sit amet velit egestas, fringilla gravida nisl aliquet.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In purus justo, aliquet et felis vel, finibus sollicitudin odio. Nullam massa lectus, rhoncus non feugiat eget, sollicitudin ut neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum et tellus bibendum, tempor lacus id, scelerisque sem. Vestibulum enim ipsum, interdum ac sem vel, facilisis venenatis ligula. Suspendisse a arcu et leo viverra euismod sed sit amet lacus. Suspendisse ac dolor porta, dictum arcu vel, suscipit tortor. Vivamus scelerisque libero ac purus sollicitudin congue. Donec a sem diam. In nec convallis felis. Praesent efficitur libero blandit turpis blandit finibus. Pellentesque fringilla lobortis aliquet. Praesent et ligula velit. Duis rutrum leo eget lectus ultrices, eget facilisis nunc condimentum. Pellentesque malesuada purus vitae commodo tristique. Cras vel posuere velit.

Morbi laoreet venenatis lorem et mattis. Vestibulum id ex et nisl condimentum tincidunt eu sit amet urna. Phasellus quis orci ut tortor lobortis eleifend. Nulla convallis lacus mauris, et porttitor sem blandit nec. Aliquam suscipit ligula quis felis finibus, sed interdum urna ultrices. Quisque massa velit, pellentesque interdum dictum ut, egestas sed sapien. Nulla ultrices nunc at turpis laoreet accumsan. Aenean ex lacus, pellentesque et auctor vitae, mollis vel ligula. Nam nisi elit, mattis vitae tincidunt at, volutpat quis ex. Ut eu lectus ut sem efficitur posuere. Praesent pretium nulla lectus, luctus scelerisque risus sollicitudin eget. Nam euismod auctor dolor non blandit. Donec eu tristique turpis, vel ornare arcu.

Vivamus posuere lorem tortor, in vulputate quam convallis eu. Nullam in mauris ex. Maecenas sollicitudin suscipit tellus vitae eleifend. In vitae felis ac mauris malesuada dignissim. In vulputate molestie dolor eget laoreet. Nunc sagittis accumsan felis, at molestie sapien lobortis vel. Nunc volutpat in velit nec pretium. Sed porta posuere orci, ac varius est. Nam viverra diam eu consectetur sagittis. Vivamus porta faucibus ex quis sodales.

Maecenas volutpat feugiat leo ut elementum. Praesent ac orci sit amet mauris blandit semper. Fusce nibh ex, accumsan vitae odio vel, cursus scelerisque lectus. Pellentesque dignissim lacus aliquam sagittis egestas. Pellentesque elementum, augue eget commodo rhoncus, augue diam imperdiet diam, sed vehicula nunc nisi facilisis nulla. In quis lacus at enim imperdiet interdum. Etiam non nulla laoreet, aliquam ex non, vulputate sem. Donec ultricies ex eget nulla ullamcorper imperdiet. Pellentesque eget ex nec ante feugiat aliquet quis nec lacus. In porta rutrum magna, sagittis bibendum sapien auctor id. Sed nec nisi vitae nibh auctor tempor vitae at eros. Donec mauris felis, gravida pellentesque luctus quis, venenatis sed tellus. Ut id bibendum justo. Praesent porttitor felis eu volutpat rhoncus. Ut ut vehicula mi, et aliquam ante.

Vivamus sed ultricies neque. Donec quis varius lorem, quis volutpat velit. Etiam sed feugiat erat. Praesent gravida enim eu odio rutrum ullamcorper. In vitae nibh at erat luctus vehicula. Donec tincidunt felis ac augue iaculis malesuada. Pellentesque elit leo, porttitor nec vestibulum non, imperdiet in velit. Vestibulum lacinia mi nec purus condimentum consectetur. Fusce in urna non erat congue pulvinar. Aliquam erat volutpat. Nam ac luctus purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum sed venenatis enim. Nullam auctor nunc sit amet velit egestas, fringilla gravida nisl aliquet.`)
)

export default Skills;
